// Action types for dispatching
enum ActionTypes {
    SET_MEMES = "SET_MEMES",
    SET_CURRENT_MEME = "SET_CURRENT_MEME",
    APPEND_MEME = "APPEND_MEME",
    DELETE_MEME = "DELETE_MEME",
    UPDATE_MEME = "UPDATE_MEME",
    UPDATE_CONTEXT = "UPDATE_CONTEXT",
    SET_LOADING_STATE = "SET_LOADING_STATE",
    SET_ADD_MEME_STATE = "SET_ADD_MEME_STATE",
    SET_MODAL_STATE = "SET_MODAL_STATE",
    APPEND_NEW_MEME = "APPEND_NEW_MEME",
    MERGE_NEW_MEMES = "MERGE_NEW_MEMES",
}

export default ActionTypes;